    window.game.modals=function(){$.ajax({
        url:window.homeurl+'/mkmodals.php',
        success:function(data){
            $('#game').append(data);
            $('#loading').attr('style','width:70%');
            window.game.encoded();
            window.game.modalh();
        }
    })};
    window.game.r(window.game.modals);